import { createContext, useContext, useState, useCallback, ReactNode } from 'react';

type AdminLang = 'hr' | 'en';

const STORAGE_KEY = 'conwayo_admin_lang';

const translations = {
  // Sidebar nav
  'nav.dashboard': { hr: 'Dashboard', en: 'Dashboard' },
  'nav.events': { hr: 'Događaji', en: 'Events' },
  'nav.adminPanel': { hr: 'Admin Panel', en: 'Admin Panel' },
  'nav.whatsappInspector': { hr: 'WhatsApp Inspector', en: 'WhatsApp Inspector' },
  'nav.signOut': { hr: 'Odjava', en: 'Sign Out' },
  'nav.settings': { hr: 'Postavke', en: 'Profile & Settings' },

  // Dashboard
  'dashboard.welcome': { hr: 'Dobrodošli natrag', en: 'Welcome back' },
  'dashboard.subtitle': { hr: 'Evo što se događa s vašim događajima danas.', en: "Here's what's happening with your events today." },
  'dashboard.createEvent': { hr: 'Stvori događaj', en: 'Create Event' },
  'dashboard.viewingEvent': { hr: 'Pregled događaja', en: 'Viewing Event' },
  'dashboard.allEvents': { hr: 'Svi događaji', en: 'All Events' },
  'dashboard.selectEvent': { hr: 'Odaberi događaj', en: 'Select an event' },
  'dashboard.viewDetails': { hr: 'Detalji →', en: 'View Details →' },
  'dashboard.managing': { hr: 'Upravljanje', en: 'Managing' },
  'dashboard.financialOverview': { hr: 'Financijski pregled platforme', en: 'Platform Financial Overview' },
  'dashboard.financialOverviewOrg': { hr: 'Financijski pregled', en: 'Financial Overview' },
  'dashboard.ticketRevenue': { hr: 'Prihod od ulaznica', en: 'Ticket Revenue' },
  'dashboard.addonRevenue': { hr: 'Prihod od dodataka', en: 'Add-on Revenue' },
  'dashboard.totalPaidRevenue': { hr: 'Ukupni plaćeni prihod', en: 'Total Paid Revenue' },
  'dashboard.confirmed': { hr: 'Potvrđeno', en: 'Confirmed' },
  'dashboard.pending': { hr: 'Na čekanju', en: 'Pending' },
  'dashboard.paid': { hr: 'Plaćeno', en: 'Paid' },
  'dashboard.revenueBreakdown': { hr: 'Pregled prihoda', en: 'Revenue Breakdown' },
  'dashboard.total': { hr: 'Ukupno', en: 'Total' },
  'dashboard.tickets': { hr: 'Ulaznice', en: 'Tickets' },
  'dashboard.addons': { hr: 'Dodaci', en: 'Add-ons' },
  'dashboard.totalAttendees': { hr: 'Ukupno polaznika', en: 'Total Attendees' },
  'dashboard.pendingIncome': { hr: 'Prihod na čekanju', en: 'Pending Income' },
  'dashboard.awaitingPayment': { hr: 'Čeka uplatu', en: 'Awaiting payment' },
  'dashboard.acrossAllEvents': { hr: 'Kroz sve događaje', en: 'Across all events' },
  'dashboard.registeredUsers': { hr: 'Registrirani korisnici', en: 'Registered users' },
  'dashboard.recentEvents': { hr: 'Nedavni događaji', en: 'Recent Events' },
  'dashboard.recentEventsSub': { hr: 'Vaši najnoviji stvoreni događaji', en: 'Your latest created events' },
  'dashboard.noEvents': { hr: 'Još nema događaja', en: 'No events yet' },
  'dashboard.noRevenue': { hr: 'Još nema podataka o prihodima', en: 'No revenue data yet' },
  'dashboard.noRevenueSub': { hr: 'Prihodi će se prikazati nakon uplata', en: 'Revenue will appear here once payments are received' },
  'dashboard.registrations': { hr: 'Registracije', en: 'Registrations' },
  'dashboard.checkedIn': { hr: 'Prijavljeni', en: 'Checked In' },
  'dashboard.conversionRate': { hr: 'Stopa konverzije', en: 'Conversion Rate' },
  'dashboard.recentActivity': { hr: 'Nedavna aktivnost', en: 'Recent Activity' },
  'dashboard.noActivity': { hr: 'Nema nedavne aktivnosti', en: 'No recent activity' },
  'dashboard.paymentMethods': { hr: 'Načini plaćanja', en: 'Payment Methods' },
  'dashboard.stripe': { hr: 'Kartica', en: 'Card' },
  'dashboard.invoice': { hr: 'Faktura', en: 'Invoice' },
  'dashboard.topEvents': { hr: 'Najpopularniji događaji', en: 'Top Events' },
  'dashboard.noData': { hr: 'Nema podataka', en: 'No data' },
  'dashboard.registrationsTimeline': { hr: 'Vremenski prikaz registracija', en: 'Registrations Timeline' },
  'dashboard.registrationsTimelineDesc': { hr: 'Nove registracije u zadnjih 14 dana', en: 'New registrations over the last 14 days' },
  'dashboard.revenueByEvent': { hr: 'Prihod po eventu', en: 'Revenue by Event' },
  'dashboard.ticketDistribution': { hr: 'Raspodjela ulaznica', en: 'Ticket Distribution' },
  'dashboard.revenueByEventDesc': { hr: 'Prihod od plaćenih ulaznica po eventu', en: 'Paid ticket revenue per event' },
  'dashboard.ticketDistributionDesc': { hr: 'Raspodjela po vrsti ulaznice', en: 'Breakdown by ticket type' },
  'dashboard.breakdownFor': { hr: 'Raspodjela za', en: 'Breakdown for' },
  'dashboard.recentActivityDesc': { hr: 'Najnovije registracije i kupnje', en: 'Latest registrations and purchases' },
  'dashboard.reviewPending': { hr: 'Pregledaj na čekanju', en: 'Review Pending' },
  'dashboard.registeredFor': { hr: 'registriran/a za', en: 'registered for' },

  // Events
  'events.title': { hr: 'Događaji', en: 'Events' },
  'events.subtitle': { hr: 'Upravljajte svim događajima na jednom mjestu', en: 'Manage all your events in one place' },
  'events.createEvent': { hr: '+ Stvori događaj', en: '+ Create Event' },
  'events.new': { hr: 'Novi događaj', en: 'New Event' },
  'events.search': { hr: 'Pretraži događaje...', en: 'Search events...' },
  'events.filterAll': { hr: 'Svi', en: 'All' },
  'events.filterDraft': { hr: 'Nacrt', en: 'Draft' },
  'events.filterPendingApproval': { hr: 'Čeka odobrenje', en: 'Pending Approval' },
  'events.filterActive': { hr: 'Aktivni', en: 'Active' },
  'events.filterTest': { hr: 'Test', en: 'Test' },
  'events.filterCompleted': { hr: 'Završeni', en: 'Completed' },
  'events.filterArchived': { hr: 'Arhivirani', en: 'Archived' },
  'events.sortNewest': { hr: 'Datum (najnoviji)', en: 'Date (newest)' },
  'events.sortOldest': { hr: 'Datum (najstariji)', en: 'Date (oldest)' },
  'events.sortName': { hr: 'Naziv', en: 'Name' },
  'events.noEvents': { hr: 'Nema događaja', en: 'No events found' },
  'events.noEventsSubtitle': { hr: 'Stvorite svoj prvi događaj', en: 'Create your first event' },
  'events.attendees': { hr: 'polaznika', en: 'attendees' },
  'events.edit': { hr: 'Uredi', en: 'Edit' },
  'events.delete': { hr: 'Obriši', en: 'Delete' },
  'events.active': { hr: 'Aktivan', en: 'Active' },
  'events.draft': { hr: 'Nacrt', en: 'Draft' },
  'events.test': { hr: 'Test', en: 'Test' },
  'events.archived': { hr: 'Arhiviran', en: 'Archived' },

  // EventCard
  'eventCard.revenue': { hr: 'Prihod', en: 'Revenue' },
  'eventCard.pending': { hr: 'Na čekanju', en: 'Pending' },
  'eventCard.attendees': { hr: 'polaznika', en: 'attendees' },
  'eventCard.edit': { hr: 'Uredi', en: 'Edit' },
  'eventCard.delete': { hr: 'Obriši', en: 'Delete' },
  'eventCard.viewDetails': { hr: 'Detalji', en: 'Details' },

  // Status badges
  'status.active': { hr: 'Aktivan', en: 'Active' },
  'status.draft': { hr: 'Nacrt', en: 'Draft' },
  'status.test': { hr: 'Test', en: 'Test' },
  'status.completed': { hr: 'Završen', en: 'Completed' },
  'status.archived': { hr: 'Arhiviran', en: 'Archived' },
  'status.pendingApproval': { hr: 'Čeka odobrenje', en: 'Pending Approval' },
  'status.rejected': { hr: 'Odbijen', en: 'Rejected' },
  'status.upcoming': { hr: 'Uskoro', en: 'Upcoming' },
  'status.expired': { hr: 'Isteklo', en: 'Expired' },
  'status.noDates': { hr: 'Datumi nisu postavljeni', en: 'No dates set' },

  // Event Details
  'eventDetails.backToEvents': { hr: 'Natrag na događaje', en: 'Back to Events' },
  'eventDetails.edit': { hr: 'Uredi događaj', en: 'Edit Event' },
  'eventDetails.delete': { hr: 'Obriši događaj', en: 'Delete Event' },
  'eventDetails.preview': { hr: 'Pregled', en: 'Preview' },
  'eventDetails.attendees': { hr: 'Polaznici', en: 'Attendees' },
  'eventDetails.tickets': { hr: 'Ulaznice', en: 'Tickets' },
  'eventDetails.ticketTiers': { hr: 'Cjenovni razredi', en: 'Ticket Tiers' },
  'eventDetails.services': { hr: 'Usluge', en: 'Services' },
  'eventDetails.approvals': { hr: 'Odobrenja', en: 'Approvals' },
  'eventDetails.overview': { hr: 'Pregled', en: 'Overview' },
  'eventDetails.addAttendee': { hr: 'Dodaj polaznika', en: 'Add Attendee' },
  'eventDetails.exportCsv': { hr: 'Izvezi CSV', en: 'Export CSV' },
  'eventDetails.totalRevenue': { hr: 'Ukupni prihod', en: 'Total Revenue' },
  'eventDetails.totalAttendees': { hr: 'Ukupno polaznika', en: 'Total Attendees' },
  'eventDetails.checkedIn': { hr: 'Prijavljeni', en: 'Checked In' },
  'eventDetails.pending': { hr: 'Na čekanju', en: 'Pending' },
  'eventDetails.paid': { hr: 'Plaćeno', en: 'Paid' },
  'eventDetails.registrations': { hr: 'registracija', en: 'registrations' },
  'eventDetails.registeredFor': { hr: 'Registrirani za ovaj događaj', en: 'Registered for this event' },
  'eventDetails.noAttendees': { hr: 'Nema polaznika', en: 'No attendees yet' },
  'eventDetails.searchAttendees': { hr: 'Pretraži polaznike...', en: 'Search attendees...' },
  'eventDetails.status': { hr: 'Status', en: 'Status' },
  'eventDetails.submitForReview': { hr: 'Pošalji na pregled', en: 'Submit for Review' },
  'eventDetails.approve': { hr: 'Odobri', en: 'Approve' },
  'eventDetails.eventNotFound': { hr: 'Događaj nije pronađen.', en: 'Event not found.' },
  'eventDetails.actionRequired': { hr: 'Potrebna akcija – razlog admina:', en: 'Action required – reason from admin:' },
  'eventDetails.dangerZone': { hr: 'Opasna zona', en: 'Danger Zone' },
  'eventDetails.archiveDescription': { hr: 'Arhivirajte ovaj događaj kako biste ga sakrili od organizatora i polaznika.', en: 'Archive this event to hide it from organizers and attendees.' },

  // Attendees table
  'attendeeTable.title': { hr: 'Polaznici', en: 'Attendees' },
  'attendeeTable.subtitle': { hr: 'Upravljajte registracijama događaja', en: 'Manage event registrations' },
  'attendeeTable.fullName': { hr: 'Ime i prezime', en: 'Full Name' },
  'attendeeTable.name': { hr: 'Ime i prezime', en: 'Name' },
  'attendeeTable.email': { hr: 'Email', en: 'Email' },
  'attendeeTable.noEmail': { hr: 'Nema emaila', en: 'No email' },
  'attendeeTable.ticket': { hr: 'Ulaznica', en: 'Ticket' },
  'attendeeTable.payment': { hr: 'Plaćanje', en: 'Payment' },
  'attendeeTable.invoiceNumber': { hr: 'Br. ponude', en: 'Invoice #' },
  'attendeeTable.orderNumber': { hr: 'Narudžba #', en: 'Order #' },
  'attendeeTable.checkin': { hr: 'Prijava', en: 'Check-in' },
  'attendeeTable.checkedIn': { hr: 'Prijavljen', en: 'Checked In' },
  'attendeeTable.notCheckedIn': { hr: 'Nije prijavljen', en: 'Not checked in' },
  'attendeeTable.registrationDate': { hr: 'Datum registracije', en: 'Registration Date' },
  'attendeeTable.status': { hr: 'Status', en: 'Status' },
  'attendeeTable.actions': { hr: 'Akcije', en: 'Actions' },
  'attendeeTable.paid': { hr: 'Plaćeno', en: 'Paid' },
  'attendeeTable.unpaid': { hr: 'Neplaćeno', en: 'Unpaid' },
  'attendeeTable.pending': { hr: 'Na čekanju', en: 'Pending' },
  'attendeeTable.overdue': { hr: 'Kasni', en: 'Overdue' },
  'attendeeTable.all': { hr: 'Svi', en: 'All' },
  'attendeeTable.yes': { hr: 'Da', en: 'Yes' },
  'attendeeTable.no': { hr: 'Ne', en: 'No' },
  'attendeeTable.registered': { hr: 'Registriran', en: 'Registered' },
  'attendeeTable.cancelled': { hr: 'Otkazan', en: 'Cancelled' },
  'attendeeTable.group': { hr: 'Grupna', en: 'Group' },
  'attendeeTable.searchInvoice': { hr: 'Pretraži br. ponude...', en: 'Search invoice #...' },
  'attendeeTable.addAttendee': { hr: 'Dodaj polaznika ručno', en: 'Add Attendee Manually' },
  'attendeeTable.addFirst': { hr: 'Dodaj prvog polaznika', en: 'Add First Attendee' },
  'attendeeTable.noRegistrations': { hr: 'Još nema registracija', en: 'No registrations yet' },
  'attendeeTable.noRegistrationsDesc': { hr: 'Dodajte polaznike ručno ili pričekajte WhatsApp registracije.', en: 'Add attendees manually or wait for WhatsApp registrations.' },
  'attendeeTable.copied': { hr: 'Kopirano u međuspremnik', en: 'Copied to clipboard' },
  'attendeeTable.clickToCopy': { hr: 'Klikni za kopiranje', en: 'Click to copy' },
  'attendeeTable.deleteAttendee': { hr: 'Obriši polaznika', en: 'Delete Attendee' },
  'attendeeTable.confirmDelete': { hr: 'Jeste li sigurni?', en: 'Are you sure?' },
  'attendeeTable.confirmDeleteDesc': { hr: 'Ova akcija je nepovratna.', en: 'This action cannot be undone.' },
  'attendeeTable.cancel': { hr: 'Odustani', en: 'Cancel' },
  'attendeeTable.confirm': { hr: 'Potvrdi', en: 'Confirm' },

  // Ticket tiers table
  'ticketTiers.title': { hr: 'Cjenovni razredi', en: 'Ticket Tiers' },
  'ticketTiers.name': { hr: 'Naziv', en: 'Name' },
  'ticketTiers.price': { hr: 'Cijena', en: 'Price' },
  'ticketTiers.capacity': { hr: 'Kapacitet', en: 'Capacity' },
  'ticketTiers.unlimited': { hr: 'Neograničeno', en: 'Unlimited' },
  'ticketTiers.salesPeriod': { hr: 'Razdoblje prodaje', en: 'Sales Period' },
  'ticketTiers.notSet': { hr: 'Nije postavljeno', en: 'Not set' },
  'ticketTiers.open': { hr: 'Otvoreno', en: 'Open' },
  'ticketTiers.ongoing': { hr: 'U tijeku', en: 'Ongoing' },
  'ticketTiers.status': { hr: 'Status', en: 'Status' },
  'ticketTiers.erpCode': { hr: 'ERP kod', en: 'ERP Code' },
  'ticketTiers.erpPlaceholder': { hr: 'ERP kod', en: 'ERP code' },
  'ticketTiers.missingErp': { hr: 'Nedostaje ERP kod', en: 'Missing ERP Code' },
  'ticketTiers.actions': { hr: 'Akcije', en: 'Actions' },
  'ticketTiers.sold': { hr: 'Prodano', en: 'Sold' },
  'ticketTiers.addTier': { hr: 'Dodaj razred', en: 'Add Tier' },
  'ticketTiers.addTicketTier': { hr: 'Dodaj cjenovni razred', en: 'Add Ticket Tier' },
  'ticketTiers.deleteTier': { hr: 'Obriši cjenovni razred', en: 'Delete Ticket Tier' },
  'ticketTiers.deleteConfirm': { hr: 'Jeste li sigurni da želite obrisati ovaj cjenovni razred? Ova akcija je nepovratna.', en: 'Are you sure you want to delete this ticket tier? This action cannot be undone.' },
  'ticketTiers.delete': { hr: 'Obriši', en: 'Delete' },
  'ticketTiers.cancel': { hr: 'Odustani', en: 'Cancel' },
  'ticketTiers.noTiers': { hr: 'Još nema konfiguriranih cjenovnih razreda.', en: 'No ticket tiers configured yet.' },
  'ticketTiers.noTiersSub': { hr: 'Dodajte svoj prvi cjenovni razred za početak prodaje.', en: 'Add your first ticket tier to start selling.' },
  'ticketTiers.translate': { hr: 'Prevedi na engleski', en: 'Translate to English' },
  'ticketTiers.translationUpdated': { hr: 'Prijevod ažuriran', en: 'Translation updated' },
  'ticketTiers.translationFailed': { hr: 'Prijevod neuspješan', en: 'Translation failed' },
  'ticketTiers.lockedTooltip': { hr: 'Ne možete uređivati naziv/cijenu — ulaznice su već prodane. Možete promijeniti kapacitet ili završiti prodaju ranije.', en: 'Cannot edit name/price — tickets already sold. You can change capacity or end sales early.' },
  'ticketTiers.deletedSuccess': { hr: 'Cjenovni razred uspješno obrisan', en: 'Ticket tier deleted successfully' },
  'ticketTiers.deleteFailed': { hr: 'Brisanje cjenovnog razreda neuspješno', en: 'Failed to delete ticket tier' },
  'ticketTiers.erpUpdated': { hr: 'ERP kod ažuriran', en: 'ERP code updated' },
  'ticketTiers.erpUpdateFailed': { hr: 'Ažuriranje ERP koda neuspješno', en: 'Failed to update ERP code' },

  // Admin Panel
  'admin.title': { hr: 'Admin Panel', en: 'Admin Panel' },
  'admin.subtitle': { hr: 'Upravljajte institucijama i korisnicima', en: 'Manage institutions and users' },
  'admin.systemUsers': { hr: 'Sistemski korisnici', en: 'System Users' },
  'admin.systemUsersSub': { hr: 'Upravljajte korisnicima platforme na svim razinama', en: 'Manage platform users across all tiers' },
  'admin.institutions': { hr: 'Institucije', en: 'Institutions' },
  'admin.users': { hr: 'Korisnici', en: 'Users' },
  'admin.addInstitution': { hr: 'Dodaj instituciju', en: 'Add Institution' },
  'admin.createInstitution': { hr: 'Stvori instituciju', en: 'Create Institution' },
  'admin.inviteUser': { hr: 'Pozovi korisnika', en: 'Invite User' },
  'admin.searchInstitutions': { hr: 'Pretraži institucije...', en: 'Search institutions...' },
  'admin.searchUsers': { hr: 'Pretraži po telefonu, imenu, emailu ili instituciji... (automatski mijenja karticu)', en: 'Search by phone, name, email, or institution... (auto-switches to matching tab)' },
  'admin.noInstitutions': { hr: 'Još nema registriranih institucija.', en: 'No institutions registered yet.' },
  'admin.noUsers': { hr: 'Nema korisnika', en: 'No users found' },
  'admin.registeredInstitutions': { hr: 'Registrirane institucije', en: 'Registered Institutions' },

  // Institutions table
  'institution.name': { hr: 'Naziv', en: 'Name' },
  'institution.oib': { hr: 'OIB', en: 'OIB' },
  'institution.address': { hr: 'Adresa', en: 'Address' },
  'institution.city': { hr: 'Grad', en: 'City' },
  'institution.country': { hr: 'Država', en: 'Country' },
  'institution.invoiceEmail': { hr: 'Email za fakture', en: 'Invoice Email' },
  'institution.users': { hr: 'Korisnici', en: 'Users' },
  'institution.events': { hr: 'Događaji', en: 'Events' },
  'institution.actions': { hr: 'Akcije', en: 'Actions' },
  'institution.edit': { hr: 'Uredi', en: 'Edit' },
  'institution.delete': { hr: 'Obriši', en: 'Delete' },
  'institution.confirmDelete': { hr: 'Jeste li sigurni da želite obrisati ovu instituciju?', en: 'Are you sure you want to delete this institution?' },

  // Users table / categories
  'user.name': { hr: 'Ime i prezime', en: 'Name' },
  'user.email': { hr: 'Email', en: 'Email' },
  'user.phone': { hr: 'Telefon', en: 'Phone' },
  'user.phoneNumber': { hr: 'Broj telefona', en: 'Phone Number' },
  'user.role': { hr: 'Uloga', en: 'Role' },
  'user.institution': { hr: 'Institucija', en: 'Institution' },
  'user.organization': { hr: 'Organizacija', en: 'Organization' },
  'user.contactPerson': { hr: 'Osoba za kontakt', en: 'Contact Person' },
  'user.status': { hr: 'Status', en: 'Status' },
  'user.actions': { hr: 'Akcije', en: 'Actions' },
  'user.active': { hr: 'Aktivan', en: 'Active' },
  'user.pending': { hr: 'Na čekanju', en: 'Pending' },
  'user.approve': { hr: 'Odobri', en: 'Approve' },
  'user.removeAccess': { hr: 'Ukloni pristup', en: 'Remove Access' },
  'user.impersonate': { hr: 'Prijavi se kao', en: 'Login as' },
  'user.allUsers': { hr: 'Svi korisnici', en: 'All Users' },
  'user.pendingApproval': { hr: 'Čekaju odobrenje', en: 'Pending Approval' },
  'user.pendingApprovals': { hr: 'Čekaju odobrenje', en: 'Pending Approvals' },
  'user.pendingApprovalsDesc': { hr: 'Nove registracije čekaju dodjelu institucije i odobrenje.', en: 'New registrations awaiting institution assignment and approval.' },
  'user.noPendingMatch': { hr: 'Nema korisnika koji odgovaraju pretrazi.', en: 'No pending users match your search.' },
  'user.noPendingClear': { hr: 'Nema zahtjeva na čekanju. Sve čisto!', en: 'No pending approvals. All clear!' },
  'user.platformClients': { hr: 'Klijenti platforme', en: 'Platform Clients' },
  'user.platformClientsFull': { hr: 'Klijenti platforme (Organizatori)', en: 'Platform Clients (Organizers)' },
  'user.platformClientsDesc': { hr: 'Tvrtke i institucije koje plaćaju softver. Imaju puni pristup nadzornoj ploči.', en: 'Companies and institutions paying for the software. They have full dashboard access.' },
  'user.noOrganizersMatch': { hr: 'Nema organizatora koji odgovaraju pretrazi.', en: 'No organizers match your search.' },
  'user.noOrganizers': { hr: 'Nema pronađenih organizatora.', en: 'No organizers found.' },
  'user.whatsappAttendees': { hr: 'WhatsApp polaznici', en: 'WhatsApp Attendees' },
  'user.whatsappAttendeesDesc': { hr: 'Krajnji korisnici koji komuniciraju samo putem WhatsAppa. NEMAJU pristup nadzornoj ploči.', en: 'End users who interact only via WhatsApp. They do NOT have dashboard access.' },
  'user.noAttendeesMatch': { hr: 'Nema polaznika koji odgovaraju pretrazi.', en: 'No attendees match your search.' },
  'user.noAttendees': { hr: 'Nema pronađenih polaznika.', en: 'No attendees found.' },
  'user.conveyoTeam': { hr: 'Conwayo tim', en: 'Conveyo Team' },
  'user.conveyoTeamDesc': { hr: 'Interni članovi tima sa super admin ovlastima.', en: 'Internal team members with super admin privileges.' },
  'user.noTeamMatch': { hr: 'Nema članova tima koji odgovaraju pretrazi.', en: 'No team members match your search.' },
  'user.noTeam': { hr: 'Nema pronađenih članova tima.', en: 'No team members found.' },
  'user.tabPending': { hr: 'Na čekanju', en: 'Pending' },
  'user.tabClients': { hr: 'Klijenti', en: 'Clients' },
  'user.tabAttendees': { hr: 'Polaznici', en: 'Attendees' },
  'user.tabTeam': { hr: 'Tim', en: 'Team' },
  'user.registered': { hr: 'Registriran', en: 'Registered' },
  'user.joined': { hr: 'Pridružio se', en: 'Joined' },
  'user.lastActive': { hr: 'Zadnja aktivnost', en: 'Last Active' },
  'user.whatsapp': { hr: 'WhatsApp', en: 'WhatsApp' },
  'user.none': { hr: 'Nema', en: 'None' },
  'user.superAdmin': { hr: 'SUPER ADMIN', en: 'SUPER ADMIN' },
  'user.admins': { hr: 'Administratori', en: 'Admins' },
  'user.organizers': { hr: 'Organizatori', en: 'Organizers' },

  // User Details Modal
  'userDetails.title': { hr: 'Detalji korisnika', en: 'User Details' },
  'userDetails.unknown': { hr: 'Nepoznat korisnik', en: 'Unknown User' },
  'userDetails.whatsappActive': { hr: 'WhatsApp aktivan', en: 'WhatsApp Active' },
  'userDetails.noPhone': { hr: 'Nema broja telefona', en: 'No phone number' },
  'userDetails.noEmail': { hr: 'Nema emaila', en: 'No email' },
  'userDetails.joined': { hr: 'Pridružio se', en: 'Joined' },
  'userDetails.unknownDate': { hr: 'Nepoznato', en: 'Unknown' },
  'userDetails.eventHistory': { hr: 'Povijest događaja', en: 'Event History' },
  'userDetails.events': { hr: 'događaja', en: 'events' },
  'userDetails.event': { hr: 'događaj', en: 'event' },
  'userDetails.noEvents': { hr: 'Ovaj korisnik još nije sudjelovao na nijednom događaju.', en: 'This user has not attended any events yet.' },
  'userDetails.attendedSummary': { hr: 'Ovaj korisnik je sudjelovao na', en: 'This user has attended' },
  'userDetails.unknownEvent': { hr: 'Nepoznat događaj', en: 'Unknown Event' },
  'userDetails.dateTbd': { hr: 'Datum nije određen', en: 'Date TBD' },

  // Modals - Invite User
  'inviteUser.title': { hr: 'Pozovi novog korisnika', en: 'Invite New User' },
  'inviteUser.description': { hr: 'Pošaljite pozivnicu na email za dodavanje novog korisnika na platformu.', en: 'Send an invitation email to add a new user to the platform.' },
  'inviteUser.firstName': { hr: 'Ime', en: 'First Name' },
  'inviteUser.lastName': { hr: 'Prezime', en: 'Last Name' },
  'inviteUser.email': { hr: 'Email adresa', en: 'Email Address' },
  'inviteUser.role': { hr: 'Uloga', en: 'Role' },
  'inviteUser.selectRole': { hr: 'Odaberite ulogu', en: 'Select a role' },
  'inviteUser.roleSuperAdmin': { hr: 'Super Admin', en: 'Super Admin' },
  'inviteUser.roleAdmin': { hr: 'Admin', en: 'Admin' },
  'inviteUser.roleOrganizer': { hr: 'Event Organizer', en: 'Event Organizer' },
  'inviteUser.institution': { hr: 'Institucija (opcionalno)', en: 'Institution (Optional)' },
  'inviteUser.selectInstitution': { hr: 'Odaberite instituciju', en: 'Select an institution' },
  'inviteUser.noInstitution': { hr: 'Bez institucije', en: 'No institution' },
  'inviteUser.submit': { hr: 'Pošalji pozivnicu', en: 'Send Invitation' },
  'inviteUser.sending': { hr: 'Slanje...', en: 'Sending...' },
  'inviteUser.cancel': { hr: 'Odustani', en: 'Cancel' },
  'inviteUser.success': { hr: 'Pozivnica poslana! Korisnik će dobiti email za postavljanje lozinke.', en: 'Invitation sent! The user will receive an email to set their password.' },

  // Modals - Approve User
  'approveUser.title': { hr: 'Odobri korisnika', en: 'Approve User' },
  'approveUser.user': { hr: 'Korisnik', en: 'User' },
  'approveUser.assignInstitution': { hr: 'Dodijeli instituciji *', en: 'Assign to Institution *' },
  'approveUser.selectInstitution': { hr: 'Odaberite instituciju', en: 'Select an institution' },
  'approveUser.selectFirst': { hr: 'Molimo odaberite instituciju', en: 'Please select an institution' },
  'approveUser.note': { hr: 'Korisniku će biti dodijeljena uloga', en: 'The user will be assigned the' },
  'approveUser.noteRole': { hr: 'Event Organizer', en: 'Event Organizer' },
  'approveUser.noteSuffix': { hr: 'i bit će povezan s odabranom institucijom.', en: 'role and linked to the selected institution.' },
  'approveUser.approve': { hr: 'Odobri i dodijeli', en: 'Approve & Assign' },
  'approveUser.cancel': { hr: 'Odustani', en: 'Cancel' },
  'approveUser.successSuffix': { hr: 'odobren kao Event Organizer', en: 'approved as Event Organizer' },

  // Modals - Create/Edit Institution
  'institutionModal.createTitle': { hr: 'Stvori novu instituciju', en: 'Create New Institution' },
  'institutionModal.editTitle': { hr: 'Uredi instituciju', en: 'Edit Institution' },
  'institutionModal.companyName': { hr: 'Naziv tvrtke', en: 'Company Name' },
  'institutionModal.oib': { hr: 'OIB (porezni broj)', en: 'OIB (Tax ID)' },
  'institutionModal.address': { hr: 'Adresa', en: 'Address' },
  'institutionModal.city': { hr: 'Grad', en: 'City' },
  'institutionModal.postalCode': { hr: 'Poštanski broj', en: 'Postal Code' },
  'institutionModal.country': { hr: 'Država', en: 'Country' },
  'institutionModal.invoiceEmail': { hr: 'Email za fakture', en: 'Invoice Email' },
  'institutionModal.website': { hr: 'Web stranica', en: 'Website' },
  'institutionModal.save': { hr: 'Spremi', en: 'Save' },
  'institutionModal.create': { hr: 'Stvori instituciju', en: 'Create Institution' },
  'institutionModal.creating': { hr: 'Stvaranje...', en: 'Creating...' },
  'institutionModal.cancel': { hr: 'Odustani', en: 'Cancel' },
  'institutionModal.successCreated': { hr: 'Institucija uspješno stvorena!', en: 'Institution created successfully!' },

  // Remove access confirmation
  'removeAccess.title': { hr: 'Ukloniti admin pristup?', en: 'Remove admin access?' },
  'removeAccess.desc': { hr: 'Ovo će u potpunosti ukloniti korisnika iz admin portala.', en: 'This will remove the user from the admin portal entirely.' },
  'removeAccess.confirm': { hr: 'Ukloni', en: 'Remove' },
  'removeAccess.cancel': { hr: 'Odustani', en: 'Cancel' },
  'user.superAdminDesc': { hr: 'Globalni administratori platforme s punim pristupom.', en: 'Global platform administrators with full access.' },
  'user.adminsOrganizersTitle': { hr: 'Administratori i organizatori događaja', en: 'Admins & Event Organizers' },
  'user.adminsOrganizersDesc': { hr: 'Administratori platforme i organizatori događaja klijenata.', en: 'Platform admins and client event organizers.' },
  'user.noSuperAdminsMatch': { hr: 'Nijedan super admin ne odgovara pretrazi.', en: 'No super admins match your search.' },
  'user.noSuperAdmins': { hr: 'Nema super administratora.', en: 'No super admins found.' },
  'user.noUsersMatch': { hr: 'Nijedan korisnik ne odgovara pretrazi.', en: 'No users match your search.' },
  'user.noAdminsOrganizers': { hr: 'Nema administratora ili organizatora.', en: 'No admins or organizers found.' },
  'user.conveyoTeamFull': { hr: 'Conwayo tim', en: 'Conveyo Team' },
  // user.conveyoTeamDesc already defined above
  'user.removeUserPortal': { hr: 'Korisnik uklonjen iz admin portala', en: 'User removed from admin portal' },
  'user.roleUpdated': { hr: 'Uloga ažurirana', en: 'Role updated' },

  // WhatsApp Inspector
  'whatsapp.title': { hr: 'WhatsApp Inspector', en: 'WhatsApp Inspector' },
  'whatsapp.subtitle': { hr: 'Pratite sve WhatsApp razgovore s AI botom', en: 'Monitor all WhatsApp conversations with the AI bot' },
  'whatsapp.conversations': { hr: 'Razgovori', en: 'Conversations' },
  'whatsapp.live': { hr: 'Uživo', en: 'Live' },
  'whatsapp.searchSessions': { hr: 'Pretraži sesije...', en: 'Search sessions...' },
  'whatsapp.noSessions': { hr: 'Nema aktivnih sesija', en: 'No active sessions' },
  'whatsapp.noMessagesFound': { hr: 'Nema poruka', en: 'No messages' },
  'whatsapp.noMatch': { hr: 'Nema razgovora koji odgovaraju filteru', en: 'No conversations match this filter' },
  'whatsapp.selectSession': { hr: 'Odaberi razgovor za pregled poruka', en: 'Select a conversation to view messages' },
  'whatsapp.event': { hr: 'Događaj', en: 'Event' },
  'whatsapp.step': { hr: 'Korak', en: 'Step' },
  'whatsapp.status': { hr: 'Status', en: 'Status' },
  'whatsapp.lastMessage': { hr: 'Zadnja poruka', en: 'Last message' },
  'whatsapp.allEvents': { hr: 'Svi događaji', en: 'All Events' },
  'whatsapp.filterByEvent': { hr: 'Filtriraj po događaju', en: 'Filter by event' },
  'whatsapp.phone': { hr: 'Telefon', en: 'Phone' },
  'whatsapp.noMessages': { hr: 'Nema poruka', en: 'No messages' },
  'whatsapp.resetSession': { hr: 'Resetiraj sesiju', en: 'Reset Session' },
  'whatsapp.confirmReset': { hr: 'Jeste li sigurni da želite resetirati ovu sesiju?', en: 'Are you sure you want to reset this session?' },
  'whatsapp.session': { hr: 'Sesija', en: 'Session' },
  'whatsapp.sessionState': { hr: 'Stanje sesije', en: 'Session State' },
  'whatsapp.noActiveSession': { hr: 'Nema aktivne sesije', en: 'No active session' },
  'whatsapp.name': { hr: 'Ime', en: 'Name' },
  'whatsapp.payerType': { hr: 'Tip platitelja', en: 'Payer Type' },
  'whatsapp.payment': { hr: 'Plaćanje', en: 'Payment' },
  'whatsapp.regType': { hr: 'Tip registracije', en: 'Reg. Type' },
  'whatsapp.cartItems': { hr: 'Stavke u košarici', en: 'Cart Items' },
  'whatsapp.services': { hr: 'Usluge', en: 'Services' },
  'whatsapp.nextAction': { hr: 'Sljedeća akcija', en: 'Next Action' },
  'whatsapp.updated': { hr: 'Ažurirano', en: 'Updated' },
  'whatsapp.today': { hr: 'Danas', en: 'Today' },
  'whatsapp.yesterday': { hr: 'Jučer', en: 'Yesterday' },
  'whatsapp.justNow': { hr: 'Upravo', en: 'Just now' },

  // Settings
  'settings.title': { hr: 'Postavke', en: 'Settings' },
  'settings.subtitle': { hr: 'Upravljajte svojim računom i postavkama', en: 'Manage your account and preferences' },
  'settings.profile': { hr: 'Korisnički profil', en: 'User Profile' },
  'settings.profileDesc': { hr: 'Vaši osobni podaci o računu', en: 'Your personal account details' },
  'settings.firstName': { hr: 'Ime', en: 'First Name' },
  'settings.lastName': { hr: 'Prezime', en: 'Last Name' },
  'settings.fullName': { hr: 'Ime i prezime', en: 'Full Name' },
  'settings.email': { hr: 'Email', en: 'Email' },
  'settings.phone': { hr: 'Telefon', en: 'Phone' },
  'settings.notSet': { hr: 'Nije postavljeno', en: 'Not set' },
  'settings.role': { hr: 'Uloga', en: 'Role' },
  'settings.edit': { hr: 'Uredi', en: 'Edit' },
  'settings.save': { hr: 'Spremi', en: 'Save' },
  'settings.cancel': { hr: 'Odustani', en: 'Cancel' },
  'settings.saveChanges': { hr: 'Spremi promjene', en: 'Save Changes' },
  'settings.profileUpdated': { hr: 'Profil uspješno ažuriran!', en: 'Profile updated successfully!' },
  'settings.profileUpdateFailed': { hr: 'Ažuriranje profila neuspješno', en: 'Failed to update profile' },
  'settings.myInstitution': { hr: 'Moja institucija', en: 'My Institution' },
  'settings.institutionDesc': { hr: 'Detalji vaše povezane organizacije', en: 'Your linked organization details' },
  'settings.companyName': { hr: 'Naziv tvrtke', en: 'Company Name' },
  'settings.vatOib': { hr: 'OIB / Porezni broj', en: 'VAT Number / OIB' },
  'settings.address': { hr: 'Adresa', en: 'Address' },
  'settings.invoiceEmail': { hr: 'Email za fakture', en: 'Invoice Email' },
  'settings.website': { hr: 'Web stranica', en: 'Website' },
  'settings.noInstitution': { hr: 'Nema povezane institucije', en: 'No institution linked' },
  'settings.contactAdmin': { hr: 'Kontaktirajte administratora za dodjelu organizacije.', en: 'Contact an admin to assign you to an organization.' },

  // Auth page
  'auth.welcomeBack': { hr: 'Dobrodošli natrag', en: 'Welcome Back' },
  'auth.subtitle': { hr: 'Unesite podatke za pristup nadzornoj ploči', en: 'Enter your credentials to access your dashboard' },
  'auth.email': { hr: 'Email', en: 'Email' },
  'auth.password': { hr: 'Lozinka', en: 'Password' },
  'auth.login': { hr: 'Prijava', en: 'Log In' },
  'auth.loggingIn': { hr: 'Molimo pričekajte...', en: 'Please wait...' },
  'auth.forgotPassword': { hr: 'Zaboravili ste lozinku?', en: 'Forgot password?' },
  'auth.invalidEmail': { hr: 'Neispravan email', en: 'Invalid Email' },
  'auth.invalidPassword': { hr: 'Neispravna lozinka', en: 'Invalid Password' },
  'auth.loginFailed': { hr: 'Prijava neuspješna', en: 'Login Failed' },
  'auth.invalidCredentials': { hr: 'Neispravan email ili lozinka. Pokušajte ponovno.', en: 'Invalid email or password. Please try again.' },
  'auth.welcomeToast': { hr: 'Dobrodošli natrag!', en: 'Welcome back!' },
  'auth.welcomeToastDesc': { hr: 'Uspješno ste prijavljeni.', en: 'You have successfully logged in.' },
  'auth.forgotTitle': { hr: 'Zaboravljena lozinka', en: 'Forgot Password' },
  'auth.forgotDesc': { hr: 'Kontaktirajte administratora za resetiranje lozinke.', en: 'Please contact your administrator to reset your password.' },

  // Pending approval
  'pending.title': { hr: 'Čeka odobrenje', en: 'Pending Approval' },
  'pending.subtitle': { hr: 'Vaš račun je registriran, ali čeka odobrenje administratora.', en: 'Your account has been registered but is awaiting approval by an administrator.' },
  'pending.detail': { hr: 'Nakon odobrenja i dodjele instituciji, imat ćete puni pristup Conwayo nadzornoj ploči.', en: "Once approved and assigned to an institution, you'll have full access to the Conwayo dashboard." },
  'pending.signOut': { hr: 'Odjava', en: 'Sign Out' },

  // Edit / Create Event form
  'editEvent.backToEvent': { hr: 'Natrag na događaj', en: 'Back to Event' },
  'editEvent.backToEvents': { hr: 'Natrag na događaje', en: 'Back to Events' },
  'editEvent.title': { hr: 'Uredi događaj', en: 'Edit Event' },
  'editEvent.createTitle': { hr: 'Stvori novi događaj', en: 'Create New Event' },
  'editEvent.lockedNotice': { hr: '⚠️ Neka polja su zaključana jer su ulaznice već prodane. Možete i dalje ažurirati opis, brendiranje, info za podršku i dostupnost cjenovnih razreda.', en: '⚠️ Some fields are locked because tickets have already been sold. You can still update description, branding, support info, and ticket tier availability.' },
  'editEvent.eventNotFound': { hr: 'Događaj nije pronađen.', en: 'Event not found.' },
  // Section titles
  'editEvent.sectionDetails': { hr: 'Detalji događaja', en: 'Event Details' },
  'editEvent.sectionDetailsDesc': { hr: 'Osnovne informacije o događaju', en: 'Basic information about your event' },
  'editEvent.sectionLocation': { hr: 'Lokacija', en: 'Location' },
  'editEvent.sectionLocationDesc': { hr: 'Gdje će se događaj održati?', en: 'Where will the event take place?' },
  'editEvent.sectionDates': { hr: 'Datumi i postavke naplate', en: 'Dates & Billing Settings' },
  'editEvent.sectionDatesDesc': { hr: 'Konfigurirajte vrijeme događaja i uvjete plaćanja', en: 'Configure event timing and payment terms' },
  'editEvent.sectionFinancials': { hr: 'Financije i postavke', en: 'Financials & Settings' },
  'editEvent.sectionFinancialsDesc': { hr: 'Financijska konfiguracija i Business Central integracija', en: 'Financial configuration and Business Central integration' },
  'editEvent.sectionNotifications': { hr: 'Obavijesti i podrška', en: 'Notifications & Support' },
  'editEvent.sectionAdministration': { hr: 'Administracija', en: 'Administration' },
  'editEvent.sectionErpCodes': { hr: 'ERP kodovi (Admin)', en: 'ERP Codes (Admin)' },
  'editEvent.sectionErpCodesDesc': { hr: 'Dodijelite ERP kodove prije odobravanja ovog događaja', en: 'Assign ERP codes before approving this event' },
  // Field labels
  'editEvent.institution': { hr: 'Institucija *', en: 'Institution *' },
  'editEvent.institutionDesc': { hr: 'Odaberite koja institucija je vlasnik ovog događaja', en: 'Choose which institution owns this event' },
  'editEvent.selectInstitution': { hr: 'Odaberite instituciju', en: 'Select an institution' },
  'editEvent.shortName': { hr: 'Kratki naziv', en: 'Short Name' },
  'editEvent.website': { hr: 'Web stranica', en: 'Website' },
  'editEvent.eventType': { hr: 'Vrsta eventa', en: 'Event Type' },
  'editEvent.venue': { hr: 'Mjesto održavanja / Venue *', en: 'Venue / Mjesto održavanja *' },
  'editEvent.venueName': { hr: 'Naziv mjesta', en: 'Venue Name' },
  'editEvent.venueAddress': { hr: 'Adresa mjesta / Venue Address', en: 'Venue Address / Adresa mjesta' },
  'editEvent.venueAddressPlaceholder': { hr: 'Ilica 1 / Ulica i broj', en: 'Ilica 1 / Street and number' },
  'editEvent.address': { hr: 'Adresa', en: 'Address' },
  'editEvent.city': { hr: 'Grad', en: 'City' },
  'editEvent.postalCode': { hr: 'Poštanski broj', en: 'Postal Code' },
  'editEvent.country': { hr: 'Država', en: 'Country' },
  'editEvent.selectCountry': { hr: 'Odaberite državu', en: 'Select country' },
  'editEvent.sectionDateTime': { hr: 'Datum i vrijeme', en: 'Date & Time' },
  'editEvent.startDate': { hr: 'Datum početka', en: 'Start Date' },
  'editEvent.endDate': { hr: 'Datum završetka', en: 'End Date' },
  'editEvent.startTime': { hr: 'Vrijeme početka', en: 'Start Time' },
  'editEvent.endTime': { hr: 'Vrijeme završetka', en: 'End Time' },
  'editEvent.optional': { hr: 'Nije obavezno / Optional', en: 'Optional / Nije obavezno' },
  'editEvent.sectionPayment': { hr: 'Plaćanje', en: 'Payment' },
  'editEvent.paymentDueDays': { hr: 'Rok plaćanja (dani)', en: 'Payment Due Days' },
  'editEvent.paymentDueDaysDesc': { hr: 'Broj dana koliko rezervacija putem bankovnog transfera ostaje važeća', en: 'Number of days a bank-transfer reservation remains valid' },
  'editEvent.status': { hr: 'Status', en: 'Status' },
  'editEvent.selectStatus': { hr: 'Odaberite status', en: 'Select status' },
  'editEvent.statusDraft': { hr: 'Nacrt', en: 'Draft' },
  'editEvent.statusPendingApproval': { hr: 'Čeka odobrenje', en: 'Pending Approval' },
  'editEvent.statusActive': { hr: 'Aktivan (objavljen)', en: 'Active (Published)' },
  'editEvent.statusCompleted': { hr: 'Završen', en: 'Completed' },
  'editEvent.currency': { hr: 'Valuta', en: 'Currency' },
  'editEvent.selectCurrency': { hr: 'Odaberite valutu', en: 'Select currency' },
  'editEvent.taxLocation': { hr: 'Porezna lokacija', en: 'Tax Location' },
  'editEvent.selectTaxLocation': { hr: 'Odaberite poreznu lokaciju', en: 'Select tax location' },
  'editEvent.taxCroatia': { hr: 'Hrvatska', en: 'Croatia' },
  'editEvent.taxEU': { hr: 'EU', en: 'EU' },
  'editEvent.taxOutsideEU': { hr: 'Izvan EU', en: 'Outside EU' },
  'editEvent.sectionERP': { hr: 'ERP integracija', en: 'ERP Integration' },
  'editEvent.bcPosition': { hr: 'BC pozicija', en: 'BC Position' },
  'editEvent.bcPositionPlaceholder': { hr: 'Referenca pozicije', en: 'Position reference' },
  'editEvent.bcReference': { hr: 'BC referenca', en: 'BC Reference' },
  'editEvent.senderName': { hr: 'Ime pošiljatelja', en: 'Sender Name' },
  'editEvent.senderNamePlaceholder': { hr: 'npr. Ivan Horvat', en: 'e.g. Ivan Horvat' },
  'editEvent.senderEmail': { hr: 'Email pošiljatelja', en: 'Sender Email' },
  'editEvent.supportPhone': { hr: 'Support telefon', en: 'Support Phone' },
  'editEvent.supportContacts': { hr: 'Kontakti podrške / Support Contacts', en: 'Support Contacts / Kontakti podrške' },
  'editEvent.supportContactsPlaceholder': { hr: 'Dodatne informacije za kontakt podrške...', en: 'Additional support contact information...' },
  'editEvent.additionalAdmins': { hr: 'Dodatni admini', en: 'Additional Admins' },
  'editEvent.additionalAdminsDesc': { hr: 'Email adrese odvojene zarezom', en: 'Comma-separated email addresses' },
  'editEvent.languages': { hr: 'Jezici eventa', en: 'Event Languages' },
  'editEvent.langPrimaryNote': { hr: 'Hrvatski je primarni jezik i ne može se ukloniti.', en: 'Croatian is the primary language and cannot be removed.' },
  'editEvent.translations': { hr: 'Prijevodi', en: 'Translations' },
  'editEvent.translationsDesc': { hr: 'Unesite engleski prijevod sadržaja eventa', en: 'Provide English translations for event content' },
  'editEvent.sectionContent': { hr: 'Sadržaj', en: 'Content' },
  'editEvent.sectionContentDesc': { hr: 'Naziv, opis i politika otkazivanja za svaki jezik', en: 'Name, description and cancellation policy per language' },
  'editEvent.nameHR': { hr: 'Naziv eventa (HR)', en: 'Event Name (HR)' },
  'editEvent.nameEN': { hr: 'Naziv eventa (EN)', en: 'Event Name (EN)' },
  'editEvent.descriptionHR': { hr: 'Opis (HR)', en: 'Description (HR)' },
  'editEvent.descriptionEN': { hr: 'Opis (EN)', en: 'Description (EN)' },
  'editEvent.cancellationHR': { hr: 'Politika otkazivanja (HR)', en: 'Cancellation Policy (HR)' },
  'editEvent.cancellationEN': { hr: 'Politika otkazivanja (EN)', en: 'Cancellation Policy (EN)' },
  'editEvent.placeholderNameEN': { hr: 'Ostavi prazno za korištenje hrvatskog naziva', en: 'Leave empty to use Croatian name' },
  'editEvent.placeholderCancellationEN': { hr: 'Ostavi prazno za korištenje hrvatske politike', en: 'Leave empty to use Croatian policy' },
  'editEvent.ticketTiers': { hr: 'Cjenovni razredi', en: 'Ticket Tiers' },
  'editEvent.services': { hr: 'Usluge', en: 'Services' },
  'editEvent.erpCodePlaceholder': { hr: 'ERP kod', en: 'ERP Code' },
  // Buttons
  'editEvent.save': { hr: 'Spremi', en: 'Save' },
  'editEvent.saveChanges': { hr: 'Spremi promjene', en: 'Save Changes' },
  'editEvent.cancel': { hr: 'Odustani', en: 'Cancel' },
  'editEvent.createEvent': { hr: 'Stvori event', en: 'Create Event' },
  // Toasts
  'editEvent.updatedSuccess': { hr: 'Događaj uspješno ažuriran!', en: 'Event updated successfully!' },
  'editEvent.updateFailed': { hr: 'Ažuriranje događaja neuspješno', en: 'Failed to update event' },
  'editEvent.createdSuccess': { hr: 'Događaj uspješno stvoren!', en: 'Event created successfully!' },
  'editEvent.createFailed': { hr: 'Stvaranje događaja neuspješno', en: 'Failed to create event' },
  'editEvent.selectInstitutionFirst': { hr: 'Molimo odaberite instituciju za ovaj događaj', en: 'Please select an institution for this event' },
  'editEvent.profileNotFound': { hr: 'Korisnički profil nije pronađen', en: 'User profile not found' },
  'editEvent.tierErpSaved': { hr: 'ERP kodovi cjenovnih razreda spremljeni', en: 'Ticket tier ERP codes saved' },
  'editEvent.serviceErpSaved': { hr: 'ERP kodovi usluga spremljeni', en: 'Service ERP codes saved' },
  'editEvent.erpSaveFailed': { hr: 'Spremanje ERP kodova neuspješno', en: 'Failed to save ERP codes' },
  // EN translation labels (kept English-explicit but bilingual labels)
  'editEvent.eventNameEn': { hr: 'Naziv događaja (EN)', en: 'Event Name (EN)' },
  'editEvent.eventDescEn': { hr: 'Opis događaja (EN)', en: 'Event Description (EN)' },
  'editEvent.cancellationPolicyEn': { hr: 'Politika otkazivanja (EN)', en: 'Cancellation Policy (EN)' },
  'editEvent.leaveEmptyName': { hr: 'Ostavite prazno za korištenje hrvatskog naziva', en: 'Leave empty to use Croatian name' },
  'editEvent.leaveEmptyDesc': { hr: 'Recite posjetiteljima više o događaju na engleskom...', en: 'Tell attendees about this event in English...' },
  'editEvent.leaveEmptyPolicy': { hr: 'Ostavite prazno za korištenje hrvatske politike', en: 'Leave empty to use Croatian policy' },

  // Data Retention
  'dataRetention.title': { hr: 'Upravljanje podacima (GDPR)', en: 'Data Management (GDPR)' },
  'dataRetention.subtitle': { hr: 'Pregled i izvođenje politike zadržavanja podataka.', en: 'Preview and run GDPR cleanup for data that has exceeded its retention period.' },
  'dataRetention.dryRunPreview': { hr: 'Pregled (dry run)', en: 'Preview (dry run)' },
  'dataRetention.messagesToDelete': { hr: 'Poruke za brisanje', en: 'Messages to delete' },
  'dataRetention.whatsappSessionsToDelete': { hr: 'WhatsApp sesije za brisanje', en: 'WhatsApp sessions to delete' },
  'dataRetention.voiceSessionsToDelete': { hr: 'Voice sesije za brisanje', en: 'Voice sessions to delete' },
  'dataRetention.attendeesToAnonymize': { hr: 'Sudionici za anonimizaciju', en: 'Attendees to anonymise' },
  'dataRetention.profilesToAnonymize': { hr: 'Profili za anonimizaciju', en: 'Profiles to anonymise' },
  'dataRetention.refreshPreview': { hr: 'Osvježi pregled', en: 'Refresh preview' },
  'dataRetention.runCleanup': { hr: 'Pokreni čišćenje', en: 'Run cleanup' },
  'dataRetention.confirmationTitle': { hr: 'Potvrda čišćenja', en: 'Cleanup confirmation' },
  'dataRetention.confirmationDesc': { hr: 'Jeste li sigurni? Ova radnja je nepovratna.', en: 'Are you sure? This action is irreversible.' },
  'dataRetention.recordsSuffix': { hr: 'zapisa bit će obrisano/anonimizirano.', en: 'records will be deleted/anonymised.' },
  'dataRetention.confirmAndRun': { hr: 'Potvrdi i pokreni', en: 'Confirm and run' },
  'dataRetention.executionHistory': { hr: 'Povijest izvođenja', en: 'Execution history' },
  'dataRetention.noExecutions': { hr: 'Nema zabilježenih izvođenja.', en: 'No executions recorded.' },
  'dataRetention.executedAt': { hr: 'Datum izvođenja', en: 'Executed at' },
  'dataRetention.chatMessages': { hr: 'Chat poruke', en: 'Chat messages' },
  'dataRetention.waSessions': { hr: 'WA sesije', en: 'WA sessions' },
  'dataRetention.voiceSessions': { hr: 'Voice sesije', en: 'Voice sessions' },
  'dataRetention.attendees': { hr: 'Sudionici', en: 'Attendees' },
  'dataRetention.profiles': { hr: 'Profili', en: 'Profiles' },
  'dataRetention.cleanupCompleted': { hr: 'Čišćenje izvršeno', en: 'Cleanup completed' },
  'dataRetention.recordsDeleted': { hr: 'Obrisano/anonimizirano:', en: 'Deleted/anonymised:' },

  // Common
  'common.save': { hr: 'Spremi', en: 'Save' },
  'common.cancel': { hr: 'Odustani', en: 'Cancel' },
  'common.delete': { hr: 'Obriši', en: 'Delete' },
  'common.edit': { hr: 'Uredi', en: 'Edit' },
  'common.loading': { hr: 'Učitavanje...', en: 'Loading...' },
  'common.error': { hr: 'Greška', en: 'Error' },
  'common.success': { hr: 'Uspješno', en: 'Success' },
  'common.confirm': { hr: 'Potvrdi', en: 'Confirm' },
  'common.search': { hr: 'Pretraži', en: 'Search' },
  'common.noResults': { hr: 'Nema rezultata', en: 'No results' },
  'common.status': { hr: 'Status', en: 'Status' },
  'common.name': { hr: 'Naziv', en: 'Name' },
  'common.email': { hr: 'Email', en: 'Email' },
  'common.phone': { hr: 'Telefon', en: 'Phone' },
  'common.actions': { hr: 'Akcije', en: 'Actions' },
  'common.close': { hr: 'Zatvori', en: 'Close' },
  'common.back': { hr: 'Natrag', en: 'Back' },
} as const;

type TranslationKey = keyof typeof translations;

interface AdminLanguageContextType {
  lang: AdminLang;
  setLang: (l: AdminLang) => void;
  t: (key: TranslationKey) => string;
}

const AdminLanguageContext = createContext<AdminLanguageContextType | null>(null);

export function AdminLanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<AdminLang>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved === 'en' || saved === 'hr') return saved;
    } catch {}
    return 'hr';
  });

  const setLang = useCallback((l: AdminLang) => {
    setLangState(l);
    try { localStorage.setItem(STORAGE_KEY, l); } catch {}
  }, []);

  const t = useCallback((key: TranslationKey): string => {
    const entry = translations[key];
    if (!entry) return key;
    return entry[lang] ?? entry['hr'] ?? key;
  }, [lang]);

  return (
    <AdminLanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </AdminLanguageContext.Provider>
  );
}

export function useAdminLanguage() {
  const ctx = useContext(AdminLanguageContext);
  if (!ctx) throw new Error('useAdminLanguage must be used within AdminLanguageProvider');
  return ctx;
}
